checkpoint_dir : 'path/of/your/checkpoints/dir'
checkpoint_path : 'path/of/your/checkpoint'
vocab_path : 'path/of/your/vocab.json'
input_dir : 'path/of/your/input/data/dir'
output_dir : 'path/of/your/output/data/dir'
device : 'gpu'